---
- name: Конфигурация пользователей
  hosts: all
  gather_facts: no
  tasks:
#     - name: user ansi presents on all hosts
#       user:
#         name: ansi
#         uid: 4000
#         comment: Ansible user
#         state: present
#         groups: wheel
#         append: yes

#     - name: доступ на все хосты для пользователя ansi
#       ansible.posix.authorized_key:
#         user: ansi
#         state: present
#         key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Создание пользователей
      user:
        name: "{{ item }}"
        comment: created by Ansible
        state: present
        groups: wheel
        append: yes
      loop:
        - ZimnyakovRS

    - name: test
      template:
      ignore_errors: yes


    - name:
      file:

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/ZimnyakovRS/.ssh
        state: directory
        mode: '0700'
        ignore_errors: yes




    - name: доступ на все хосты для пользователя {{ item.user }}
      ansible.posix.authorized_key:
        user: "{{ item.user }}"
        state: present
        key: "{{ lookup('file', '{{ item.keyf }}') }}"
      loop: {{ ssh_rsa_pub_keys }}
...