---
- name: Конфигурация пользователей
  hosts: all
  gather_facts: no
  tasks:
#     - name: user ansi presents on all hosts
#       user:
#         name: ansi
#         uid: 4000
#         comment: Ansible user
#         state: present
#         groups: wheel
#         append: yes

#     - name: доступ на все хосты для пользователя ansi
#       ansible.posix.authorized_key:
#         user: ansi
#         state: present
#         key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: user presents on all hosts
      user:
        name: "{{ item }}"
        comment: created by Ansible
        state: present
        groups: wheel
        append: yes
      loop:
        - ZimnyakovRS

    - name: доступ на все хосты для пользователя ansi
      ansible.posix.authorized_key:
        user: "{{ item.user }}"
        state: present
        key: "{{ lookup('file', 'public_keys/{{ item.keyfile }}') }}"
      loop:
        - user: ansi
          keyfile: ssh_rsa_ansi.pub
        - user: ZimnyakovRS
          keyfile: ssh_rsa_ZimnyakovRS3.pub
...