---
- name: Loops
  hosts: centos
  become: yes
  tasks:
    - name: Say hell
      debug: 
        msg: "Hello {{ item }}"
      loop:
        - "Vasia"
        - "Petia"
        - "Masha"
        - "Olia"
    
    - name: Loop Until example
      shell: "echo -n Z >> myZfile.txt && cat myZfile.txt"
      delay: 2
      retries: 10
      register: output
      until: output.stdout.find("ZZZZ") == false
      
    - name: Print final output
      debug:
        var: output.stdout
        
...